Add missing argument to init_alloc_root:
Example error message was:

mariadb-10.3.14/storage/ibmdb2i/db2i_charsetSupport.cc:169:55: error: invalid conversion from 'int' to 'const char*'
   init_alloc_root(&textDescMapMemroot, 2048, 0, MYF(0));

mariadb-10.3.14/storage/ibmdb2i/db2i_charsetSupport.cc:169:55: error: too few arguments to function 'void init_alloc_root(MEM_ROOT*, const char*, size_t, size_t, myf)'